.TH "BOGL" "1" "March 2011" "BOGL" "BOGL"
.SH NAME
reduce-font \- reduce a font to a set of glyphs
.SH SYNOPSIS
\fBreduce-font\fR \fIfont.bdf\fR < \fItext\fR
.SH DESCRIPTION
.B reduce-font
reduces the content of a font, provided the set of text that will have to be displayed with the reduced font. There is no option.
